apiVersion: v2
name: phonebook
description: A Helm chart for Phonebook Application
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: mongodb
    version: "13.x.x"
    repository: https://charts.bitnami.com/bitnami