# values-prod.yaml
app:
  replicaCount: 2
  image:
    repository: "600627353694.dkr.ecr.ap-south-1.amazonaws.com/leon/phonebook-app"
    tag: "1.0.2"

mongodb:
  architecture: replicaset
  replicaCount: 2
  auth:
    enabled: true
    existingSecret: "mongodb-credentials"
    rootUser: "admin"
    usernames: 
      - "phonebook_user"
    databases:
      - "phonebook"

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "phonebook-issuer"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: portfolioleon.ddns.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: phonebook-tls
      hosts:
        - portfolioleon.ddns.net

metrics:     
  enabled: true
  serviceMonitor:
    enabled: true