FROM mongo:8.0.4

COPY mongo-init.js /docker-entrypoint-initdb.d/
RUN chmod 644 /docker-entrypoint-initdb.d/mongo-init.js

# Use the default MongoDB entrypoint script
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["mongod", "--auth", "--logpath", "/proc/1/fd/1", "--logappend"]